site_name: ImpFo
theme: 
  name: material
  features:
    - instant
  palette:
    scheme: preference
    primary: indigo
    accent: 
repo_name: jennydove/
repo_url: https://github.com/squidfunk/mkdocs-material