site_name: LFPH Implementers Forum
theme: 
  name: material
  features:
    - instant
  palette:
    scheme: preference
    primary: indigo
    accent: 
repo_name: LFPH
repo_url: https://github.com/lfph/implementers-forum
nav:
  - 'index.md'
  - 'getting-started.md'
  - 'Documentation':
    - 'user-research.md'
    - 'analytics.md'